### PR TITLE
Updated Wallet Connect Provider

### PR DESCRIPTION
**Pull request by dacebt**

### CODE REVIEW

**Comment by adamgall** [comment]
@Da-Colon shipit

**Comment by dacebt** [comment]
@adamgall not sure what happen here with the test deployment failing?

**Comment by dacebt** [comment]
image

**Comment by adamgall** [comment]
Hmm I'm not sure either. I'm on my phone so hard to research what's going on.

Want to merge it anyway and see if the build go through in GitHub Actions?

If it doesn't work right, we can always revisit and fix it later.

**Pull request merged**
